FIT_Project_Manager/Models/ErrorViewModel.cs
namespace FIT_Project_Manager.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

FIT_Project_Manager/Models/HomeViewModel.cs
using FIT_Project_Manager.SQLlib;

namespace FIT_Project_Manager.Models
{
    public sealed class HomeViewModel
    {
        public List<DataBaseHandler.RecordData>? RecordData { get; set; }
    }
}

FIT_Project_Manager/Models/RecordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace FIT_Project_Manager.Models;

public sealed class RecordViewModel
{
    [Display(Name="タイトル")]
    [Required(ErrorMessage = "タイトルを入力してください。")]
    [StringLength(1000)]
    public string? Title { get; set; }

    [Display(Name="内容")]
    [Required(ErrorMessage = "内容を入力してください。")]
    [StringLength(1000000)]
    public string? Content { get; set; }
}

FIT_Project_Manager/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using FIT_Project_Manager.Sessionlib;
using System.ComponentModel;

namespace FIT_Project_Manager.Controllers;

public class AuthController : Controller
{
    public AuthController()
    {}

    public async Task<bool> IsLogin()
    {
        if (string.IsNullOrEmpty(SessionHandler.Get(HttpContext.Session, SessionHandler.IdAccessKey)))
        {
            return false;
        }
        return true;
    }
    public async Task<IActionResult> LogOut()
    {
        Console.WriteLine("Hello LogOut");
        SessionHandler.ClearSession(HttpContext.Session);
        return Redirect("/");
    }
}

FIT_Project_Manager/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using FIT_Project_Manager.Models;
using FIT_Project_Manager.Sessionlib;
using Microsoft.AspNetCore.Http;
using FIT_Project_Manager.SQLlib;

namespace FIT_Project_Manager.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        HomeViewModel? view_model = new HomeViewModel();
        DataBaseHandler db_handler = new DataBaseHandler();
        if (SessionHandler.IsLogin(HttpContext.Session))
        {
            Console.WriteLine("Get Record Data.");
            var response = await db_handler.GetTodayRecordDataAsync(
                Int32.Parse(
                    SessionHandler.Get(HttpContext.Session, SessionHandler.IdAccessKey)
                )
            );
            view_model.RecordData = response.RecordData;
            if (view_model.RecordData.Count == 0)
            {
                Console.WriteLine("Have not today record.");
            }
            Console.WriteLine(response.Message);
        }
        else
        {
            view_model.RecordData = null;
        }
        Console.WriteLine($"view model: {view_model.RecordData}");
       
        return View("./Views/Home/Index.cshtml", view_model);
    }

    [HttpGet]
    public async Task<IActionResult> SetSession()
    {
        string userIdKey = SessionHandler.IdAccessKey;
        string usernameKey = SessionHandler.NameAccessKey;
        if (string.IsNullOrEmpty(SessionHandler.Get(HttpContext.Session, userIdKey)))
        {
            SessionHandler.Set(HttpContext.Session, userIdKey, "2");
            SessionHandler.Set(HttpContext.Session, usernameKey, "井上優也");
        }
        Console.WriteLine($"UserID: {SessionHandler.Get(HttpContext.Session, userIdKey)}");
        Console.WriteLine($"UserName: {SessionHandler.Get(HttpContext.Session, usernameKey)}");
        return Redirect("/");
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

FIT_Project_Manager/Controllers/RecordController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using FIT_Project_Manager.Models;
using Microsoft.AspNetCore.Components.Web;
using FIT_Project_Manager.SQLlib;
using FIT_Project_Manager.Sessionlib;

namespace FIT_Project_Manager.Controllers;

public class RecordController : Controller
{
    private readonly ILogger<RecordController> _logger;

    public RecordController(ILogger<RecordController> logger)
    {
        _logger = logger;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        if (!SessionHandler.IsLogin(HttpContext.Session))
        {
            return Redirect("/");
        }
        RecordViewModel view_model = new RecordViewModel()
        { 
            Title = "",
            Content = ""
        };
        return View("./Views/Record/Index.cshtml", view_model);
    }

    [HttpPost]
    public async Task<IActionResult> RegisterRecord(RecordViewModel view_model)
    {
        if (!SessionHandler.IsLogin(HttpContext.Session))
        {
            return Redirect("/");
        }
        // TODO: サニタイズを行う, トランザクションを入れたい
        List<string> values = new List<string>();
        values.Add(view_model.Title);
        values.Add(view_model.Content);
        values.Add("0");
        DataBaseHandler db_handler = new DataBaseHandler();
        var response = await db_handler.InsertRecord(values, Int32.Parse(SessionHandler.Get(HttpContext.Session, SessionHandler.IdAccessKey)));
        Console.WriteLine($"Response Message: {response.Message}");
        if (response.Flag)
        {
            TempData["ResponseMessage"] = "記録しました。";
            TempData["ResponseClass"] = "alert alert-success";
            return Redirect("/");
        }
        TempData["ResponseMessage"] = "エラーが発生しました。";
        TempData["ResponseClass"] = "alert alert-danger";
        return View("./Views/Record/Index.cshtml", view_model);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }


}

FIT_Project_Manager/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model FIT_Project_Manager.Models.HomeViewModel
@using FIT_Project_Manager.Sessionlib
<div>
    @{
        if (!SessionHandler.IsLogin(Context.Session))
        {
            <h1><a asp-controller="Home" asp-action="SetSession">セッションをセット</a></h1>
        }
        else
        {
            <div class="fs-3 text-end">
                Name: @SessionHandler.Get(Context.Session, SessionHandler.NameAccessKey)
            </div>
            if (Model.RecordData.Count > 0)
            {
                for(int i = 0; i < Model.RecordData.Count; i++)
                {
                    string component_class = "mb-3 home-record-area";// +i.ToString();
                    @* if (i > 0) { component_class += " hidden-component"; } *@
                    <div class="@component_class">
                        <h1 class="text-start">[タイトル]</h1>
                        <div class="mb-3 text-start fs-3"><u>・ @Model.RecordData[i].Title</u></div>
                        <h1 class="text-start">[内容]</h1>
                        <div class="note">
                            <p class="text-start">@Model.RecordData[i].Content</p>
                        </div>
                    </div>
                }

                <div class="page-count-area m-2 fs-4">
                    <span class="target-page-number"></span> / <span class="max-page-number"></span>
                </div>
                
                <div class="btn-toolbar bt-3" role="toolbar" aria-label="Toolbar with button groups">
                    <div class="btn-group me-3" role="group" aria-label="Prev group">
                        <a class="circle_btn_prev">
                            <div class="circle_btn_prev_arrow"><span>&lt;</span></div>
                        </a>
                    </div>
                    <div class="btn-group" role="group" aria-label="Next group">
                        <a class="circle_btn_next">
                            <div class="circle_btn_next_arrow"><span>&gt;</span></div>
                        </a>
                    </div>
                </div>
            }
            else
            {
                <h1 class="text-center mt-5">プロジェクトを進めて記録しよう！</h1>
            }
        }
    }
</div>
@section Scripts {
    <script type="text/javascript" src="~/js/home.js"></script>
}

FIT_Project_Manager/Views/Record/Index.cshtml
@{
    ViewData["Title"] = "Record Page";
}

@model FIT_Project_Manager.Models.RecordViewModel
@* TODO: 改行が反映されていないため今後改善する *@
<h1 class="mb-3"><u>今日の進捗</u></h1>
<form method="post" asp-action="RegisterRecord">
    <div class="form-title-error-area text-danger"><span asp-validation-for="Title"></span></div>
    <div class="form-floating mb-3">
        <input asp-for="Title" type="text" class="form-control" placeholder="Leave a title here" id="floatingInputTitle" value=@Model.Title>
        <label for="floatingInputTitle">タイトル</label>
    </div>
    <div class="form-content-error-area text-danger"><span asp-validation-for="Content"></span></div>
    <div class="form-floating mb-3">
        <textarea asp-for="Content" class="form-control" id="floatingContent" placeholder="Leave a content here" style="height: 300px">@Model.Content</textarea>
        <label for="floatingContent">内容</label>
    </div>
  <button type="submit" class="btn btn-primary">提出</button>
</form>

@* TODO: jQueryを用いてサニタイズする。フォーカスが外れたときにサニタイズするのが良さそう。 *@
@* TODO: モーダルを入れる *@

FIT_Project_Manager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project_Manager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FIT_Project_Manager.styles.css" asp-append-version="true" />
    @* @RenderSectionAsync("Css", required: false) *@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom border-bottom-dark box-shadow mb-3" data-bs-thema="dark">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold text-white" asp-area="" asp-controller="Home" asp-action="Index">ProjectManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link fw-bold text-white" asp-area="" asp-controller="Home" asp-action="Index">ホーム</a>
                        </li>
                        @using FIT_Project_Manager.Sessionlib;
                        @using Microsoft.AspNetCore.Http;
                        @{
                            if (!SessionHandler.IsLogin(Context.Session))
                            {
                                <li class="nav-item">
                                    <a class="nav-link fw-bold text-white" asp-controller="" asp-action="">TODO: ログイン</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link fw-bold text-white" asp-controller="" asp-action="">TODO: サインアップ</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link fw-bold text-white" asp-controller="Record" asp-action="Index">記録</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link fw-bold text-white" asp-area="">TODO: グループ</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link fw-bold text-white" asp-area="">TODO: 設定</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link fw-bold text-white" asp-controller="Auth" asp-action="LogOut">ログアウト</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="flash-message-area @TempData["ResponseClass"] alert-dismissible fade show mb-3" role="alert">
                <span class="text-center">@TempData["ResponseMessage"]</span>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2023 - Project_Manager
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>